-- liquibase formatted sql
-- changeset fiscal:11
INSERT INTO "main"."company_naming"("nickname","name")
VALUES
    ('9 industria de','9 industria de'),
    ('a popular variedades','a popular variedades'),
    ('ambev sa - cdd piracicaba','ambev sa - cdd piracicaba'),
    ('aplos industria e comercio de bebidas eireli','aplos industria e comercio de bebidas eireli'),
    ('arroba','arroba embalagens eireli'),
    ('arroba embalagens eireli','arroba embalagens eireli'),
    ('blinde seguranca eletronica','blinde seguranca eletronica'),
    ('bravalumi group ltda','bravalumi group ltda'),
    ('camargo & gomiero indústria e comercio de fornos l','camargo & gomiero indústria e comercio de fornos l'),
    ('carrefour com. e ind. ltda','carrefour com. e ind. ltda'),
    ('comercio de ingredientes online neovita ltda.','comercio de ingredientes online neovita ltda.'),
    ('conectfrio comercio de refrigeracao e serv. ltda','conectfrio comercio de refrigeracao e serv. ltda'),
    ('carolina decico negri','carolina decico negri'),
    ('crie casa moveis e decoracao ltda','crie casa moveis e decoracao ltda'),
    ('dancha com e ser eireli','dancha comercio e servicos eireli'),
    ('dancha comercio e servicos eireli','dancha comercio e servicos eireli'),
    ('daniel luiz ribeiro - me','daniel luiz ribeiro - me'),
    ('diamante mix comercio e distribuidora ltda','diamante mix comercio e distribuidora ltda'),
    ('diamante portas e janelas ltda','diamante portas e janelas ltda'),
    ('dona alice comercio de produtos para panificacao e confeitar','dona alice comercio de produtos para panificacao e confeitar'),
    ('dorivali com dist pr alim ltda','dorivali com. dist. prod. alimenticios ltda'),
    ('dorivali com. dist. prod. alimenticios ltda','dorivali com. dist. prod. alimenticios ltda'),
    ('dulcineia balthazar redivo 22013443889','dulcineia balthazar redivo 22013443889'),
    ('decore com papel','decore com papel'),
    ('derik stevan fernandi','derik stevan fernandi'),
    ('edineia aparecida amancio 29423472877','edineia aparecida amancio 29423472877'),
    ('embafast comercio e distribuidora de embalagens ltda','embafast comercio e distribuidora de embalagens ltda'),
    ('embaleme com.emb.descartaveis ltda epp','embaleme com.emb.descartaveis ltda epp'),
    ('embramex assessoria comercialimportaca','embramex assessoria comercial imp. exp. ltda'),
    ('erlelab equipamentos para laboratorios ltda','erlelab equipamentos para laboratorios ltda'),
    ('espaco gastronomico i ltda','espaco gastronomico importadora ltda'),
    ('espaco gastronomico importadora ltda','espaco gastronomico importadora ltda'),
    ('ecocopo industria e comerc','ecocopo industria e comercio de brindes ltda'),
    ('ecocopo industria e comercio de brindes ltda','ecocopo industria e comercio de brindes ltda'),
    ('embramex assessoria comercial imp. exp. ltda','embramex assessoria comercial imp. exp. ltda'),
    ('fazenda vargem graos selecionados ind. e com. e dist. ltda','fazenda vargem graos selecionados ind. e com. e dist. ltda'),
    ('fillovita store comercio produtos alimenticios e de informat','fillovita store comercio produtos alimenticios e de informat'),
    ('frimesa cooperativa central','frimesa cooperativa central'),
    ('fabio jorge turolla','fabio jorge turolla'),
    ('facebook servicos online d','facebook servicos online d'),
    ('fernando variedades e utensilio ltda.','fernando variedades e utensilio ltda.'),
    ('frutos do pomar','frutos do pomar'),
    ('g2d automacao comercial ltda','g2d automacao comercial ltda'),
    ('galmaqui comercio de maquinas frigorificos acougues e padari','galmaqui comercio de maquinas frigorificos acougues e padari'),
    ('guilherme de mello calabresi 32246555850','guilherme de mello calabresi 32246555850'),
    ('gvc pack comercio de embalagens sociedade unipessoal ltda','gvc pack comercio de embalagens sociedade unipessoal ltda'),
    ('henrique rissardi matos eletronica','henrique rissardi matos eletronica'),
    ('hygge com. de ferragens moveis e decoracoes eireli','hygge com. de ferragens moveis e decoracoes eireli'),
    ('helena maria us','helena maria us'),
    ('hugart decoracoes ltda','hugart decoracoes ltda'),
    ('ind. de prod. metal. do nordeste s/a','ind. de prod. metal. do nordeste s/a'),
    ('laudinete tenoro de barros comercio','laudinete tenoro de barros comercio'),
    ('linpas produtos para limpeza eireli','linpas produtos para limpeza eireli'),
    ('luis ricardo batista do na','luis ricardo batista do na'),
    ('maria alice saraiva dias cabral 11918693692','maria alice saraiva dias cabral 11918693692'),
    ('meu movel de madeira com de mov e dec s.a','meu movel de madeira com de mov e dec s.a'),
    ('meu movel de madeira - com','meu movel de madeira com de mov e dec s.a'),
    ('meu movel de madeira com de mov e dec s.a movel de madeira - com', 'meu movel de madeira com de mov e dec s.a'),
    ('mobly comercio varejista ltda.','mobly comercio varejista ltda.'),
    ('magalu pagamentos ltda','magalu pagamentos ltda'),
    ('marcos ferreira da silva','marcos ferreira da silva'),
    ('maxmix comercial ltda','maxmix comercial ltda'),
    ('maxmix comercio ltda','maxmix comercial ltda'),
    ('mobly comercio varejista l','mobly comercio varejista ltda.'),
    ('monise bosqueti','monise bosqueti'),
    ('nova gibim artigos p festas e embalagens eirele me','nova gibim artigos p festas e embalagens eirele me'),
    ('nicole gabriele simoes aug','nicole gabriele simoes aug'),
    ('nova delivery','nova delivery'),
    ('omega industria e comercio de equipamentos para uso comercia','omega industria e comercio de equipamentos para uso comercia'),
    ('opus coml. imp. e export. ltda','opus coml. imp. e export. ltda'),
    ('organisys software ltda.','organisys software ltda.'),
    ('padaria delicia','padaria delicia'),
    ('plinio scalon paiva abrantes','plinio scalon paiva abrantes'),
    ('pix marketplace','pix marketplace'),
    ('r. orlando com de bebidas ltda','r. orlando com de bebidas ltda'),
    ('r. orlando comercio de bebidas','r. orlando com de bebidas ltda'),
    ('r.b.m.veloso iluminacao','r.b.m.veloso iluminacao'),
    ('ricar ind com de embalagens e transp em geral ltda','ricar ind com de embalagens e transp em geral ltda'),
    ('rosemae fernandes vohlk','rosemae fernandes vohlk'),
    ('s v comercio','s v comercio'),
    ('saint-gobain distribuicao brasil lt','saint-gobain distribuicao brasil lt'),
    ('santa efigenia e-commerce ltda','santa efigenia e-commerce ltda'),
    ('scalon & cerchi ltda','scalon & cerchi ltda'),
    ('sendas distribuidora s/a lj167','sendas distribuidora s/a lj167'),
    ('sendas distribuidora s/a lj244','sendas distribuidora s/a lj244'),
    ('spal industria brasileira de bebidas s/a','spal industria brasileira de bebidas s/a'),
    ('startek automacao indl ltda','startek automacao indl ltda'),
    ('samantha lucena santos','samantha lucena santos'),
    ('sampakraft industria e com','sampakraft industria e com'),
    ('sanval de frios ltda','sanval de frios ltda'),
    ('supermercados cavicchiolli ltda','supermercados cavicchiolli ltda'),
    ('tan qin','tan qin'),
    ('temperare equipamentos para cozinhas ltda','temperare equipamentos para cozinhas ltda'),
    ('telha norte','telha norte saint-gobain distribuicao brasil lt'),
    ('telha norte saint-gobain distribuicao brasil lt','telha norte saint-gobain distribuicao brasil lt'),
    ('tenda atacado sa','tenda atacado sa'),
    ('tok&stok','tok&stok'),
    ('uniformes blumenau ltda me','uniformes blumenau ltda me'),
    ('vanilla brasil industria e comercio de produtos alimenticios','vanilla brasil industria e comercio de produtos alimenticios'),
    ('via vizzon comercio de semi joias ltda','via vizzon comercio de semi joias ltda'),
    ('villas embalagens ltda','villas embalagens ltda'),
    ('vinicius weber verginassi','vinicius weber verginassi'),
    ('yuri peron faula de olivei','yuri peron faula de olivei'),
    ('zoop tecnologia e meios de','zoop tecnologia e meios de'),
    ('assai atacadista','sendas distribuidora s/a lj167'),
    ('vm parras filial','vm parras filial');
